/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * Gather Ends - version 1.0.0
 *
 * MoneyRoadGather EndPoints
 *
 * OpenAPI version: 3.0.0
 *
 * Contact:
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'App.AppController_getHello': ['GET', '/'],
  'User.UserController_getUserInfo': ['GET', '/user/info'],
  'User.UserController_getUsers': ['GET', '/user/users'],
  'User.UserController_register': ['POST', '/user/register'],
  'Auth.AuthController_login': ['POST', '/auth/login']
};
