/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * Gather Ends - version 1.0.0
 *
 * MoneyRoadGather EndPoints
 *
 * OpenAPI version: 3.0.0
 *
 * Contact:
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'App.AppController_getHello': ['GET', '/'],
  'User.UserController_getUserInfo': ['GET', '/user/info'],
  'User.UserController_getUsers': ['POST', '/user/users'],
  'Auth.AuthController_login': ['POST', '/auth/login'],
  'Auth.AuthController_register': ['POST', '/auth/register'],
  'Auth.AuthController_refresh': ['POST', '/auth/refresh'],
  'Auth.AuthController_getHistory': ['POST', '/auth/history'],
  'Config.ConfigController_create': ['POST', '/config'],
  'Config.ConfigController_getConfigurations': ['POST', '/config/list'],
  'Config.ConfigController_findOne': ['GET', '/config/{id}'],
  'Config.ConfigController_update': ['PATCH', '/config/{id}'],
  'Config.ConfigController_remove': ['DELETE', '/config/{id}']
};
