/* tslint:disable */
/* eslint-disable */
/**
 * Gather Ends - version 1.0.0
 *
 * MoneyRoadGather EndPoints
 *
 * OpenAPI version: 3.0.0
 *
 * Contact:
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
import type { Alova, AlovaMethodCreateConfig, AlovaGenerics, Method } from 'alova';
import type { $$userConfigMap, alovaInstance } from '.';
import type apiDefinitions from './apiDefinitions';

type CollapsedAlova = typeof alovaInstance;
type UserMethodConfigMap = typeof $$userConfigMap;

type Alova2MethodConfig<Responded> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Omit<
        AlovaMethodCreateConfig<
          AlovaGenerics<Responded, any, RequestConfig, Response, ResponseHeader, L1Cache, L2Cache, SE>,
          any,
          Responded
        >,
        'params'
      >
    : never;

// Extract the return type of transform function that define in $$userConfigMap, if it not exists, use the default type.
type ExtractUserDefinedTransformed<
  DefinitionKey extends keyof typeof apiDefinitions,
  Default
> = DefinitionKey extends keyof UserMethodConfigMap
  ? UserMethodConfigMap[DefinitionKey]['transform'] extends (...args: any[]) => any
    ? Awaited<ReturnType<UserMethodConfigMap[DefinitionKey]['transform']>>
    : Default
  : Default;
type Alova2Method<
  Responded,
  DefinitionKey extends keyof typeof apiDefinitions,
  CurrentConfig extends Alova2MethodConfig<any>
> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Method<
        AlovaGenerics<
          CurrentConfig extends undefined
            ? ExtractUserDefinedTransformed<DefinitionKey, Responded>
            : CurrentConfig['transform'] extends (...args: any[]) => any
              ? Awaited<ReturnType<CurrentConfig['transform']>>
              : ExtractUserDefinedTransformed<DefinitionKey, Responded>,
          any,
          RequestConfig,
          Response,
          ResponseHeader,
          L1Cache,
          L2Cache,
          SE
        >
      >
    : never;

export type ResultData = {
  /**
   * [required]
   */
  code: number;
  /**
   * [required]
   */
  msg: string;
};
export type UserPagniationDto = {
  /**
   * 分页页码
   * [required]
   */
  page: number;
  /**
   * 分页大小(5, 10, 20, 50, 100)
   * [required]
   */
  pageSize: number;
  /**
   * 账号名称参数
   * [required]
   */
  name: string;
  /**
   * 邮箱名称参数
   * [required]
   */
  email: string;
};
export type UserLoginProps = object;
export type CreateConfigurationDto = {
  /**
   * 命名空间
   * [required]
   */
  namespace: string;
  /**
   * 键名
   * [required]
   */
  key: string;
  /**
   * 键值
   * [required]
   */
  value: string;
  /**
   * 键值类型
   * [required]
   */
  valueType: string;
  /**
   * 键描述
   * [required]
   */
  description: string;
  /**
   * 是否公开
   * [required]
   */
  isPublic: boolean;
};
export type ConfigurationPagniationDto = {
  /**
   * 分页页码
   * [required]
   */
  page: number;
  /**
   * 分页大小(5, 10, 20, 50, 100)
   * [required]
   */
  pageSize: number;
  /**
   * 命名空间
   * [required]
   */
  namespace: string;
  /**
   * 键名
   * [required]
   */
  key: string;
  /**
   * 键值类型
   * [required]
   */
  valueType: string;
};
export type UpdateConfigDto = {
  /**
   * 命名空间
   */
  namespace?: string;
  /**
   * 键名
   */
  key?: string;
  /**
   * 键值
   */
  value?: string;
  /**
   * 键值类型
   */
  valueType?: string;
  /**
   * 键描述
   */
  description?: string;
  /**
   * 是否公开
   */
  isPublic?: boolean;
};
declare global {
  interface Apis {
    App: {
      /**
       * ---
       *
       * [GET]
       *
       * **path:** /
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      AppController_getHello<Config extends Alova2MethodConfig<unknown>>(
        config?: Config
      ): Alova2Method<unknown, 'App.AppController_getHello', Config>;
    };
    User: {
      /**
       * ---
       *
       * [GET] Get logined user info
       *
       * **path:** /user/info
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      UserController_getUserInfo<Config extends Alova2MethodConfig<unknown>>(
        config?: Config
      ): Alova2Method<unknown, 'User.UserController_getUserInfo', Config>;
      /**
       * ---
       *
       * [POST] Get users list
       *
       * **path:** /user/users
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 分页页码
       *   // [required]
       *   page: number
       *   // 分页大小(5, 10, 20, 50, 100)
       *   // [required]
       *   pageSize: number
       *   // 账号名称参数
       *   // [required]
       *   name: string
       *   // 邮箱名称参数
       *   // [required]
       *   email: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // [required]
       *   code: number
       *   // [required]
       *   msg: string
       * } & unknown
       * ```
       */
      UserController_getUsers<
        Config extends Alova2MethodConfig<ResultData & unknown> & {
          data: UserPagniationDto;
        }
      >(
        config: Config
      ): Alova2Method<ResultData & unknown, 'User.UserController_getUsers', Config>;
    };
    Auth: {
      /**
       * ---
       *
       * [POST] Login
       *
       * **path:** /auth/login
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = object
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      AuthController_login<
        Config extends Alova2MethodConfig<unknown> & {
          data: UserLoginProps;
        }
      >(
        config: Config
      ): Alova2Method<unknown, 'Auth.AuthController_login', Config>;
      /**
       * ---
       *
       * [POST] Register
       *
       * **path:** /auth/register
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = object
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      AuthController_register<
        Config extends Alova2MethodConfig<unknown> & {
          data: UserLoginProps;
        }
      >(
        config: Config
      ): Alova2Method<unknown, 'Auth.AuthController_register', Config>;
      /**
       * ---
       *
       * [POST] Refresh token
       *
       * **path:** /auth/refresh
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      AuthController_refresh<Config extends Alova2MethodConfig<unknown>>(
        config?: Config
      ): Alova2Method<unknown, 'Auth.AuthController_refresh', Config>;
      /**
       * ---
       *
       * [POST] Get user history (latest 10)
       *
       * **path:** /auth/history
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      AuthController_getHistory<Config extends Alova2MethodConfig<unknown>>(
        config?: Config
      ): Alova2Method<unknown, 'Auth.AuthController_getHistory', Config>;
    };
    Config: {
      /**
       * ---
       *
       * [POST] Create a new configuration
       *
       * **path:** /config
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 命名空间
       *   // [required]
       *   namespace: string
       *   // 键名
       *   // [required]
       *   key: string
       *   // 键值
       *   // [required]
       *   value: string
       *   // 键值类型
       *   // [required]
       *   valueType: string
       *   // 键描述
       *   // [required]
       *   description: string
       *   // 是否公开
       *   // [required]
       *   isPublic: boolean
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      ConfigController_create<
        Config extends Alova2MethodConfig<unknown> & {
          data: CreateConfigurationDto;
        }
      >(
        config: Config
      ): Alova2Method<unknown, 'Config.ConfigController_create', Config>;
      /**
       * ---
       *
       * [POST] Get configuration list
       *
       * **path:** /config/list
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 分页页码
       *   // [required]
       *   page: number
       *   // 分页大小(5, 10, 20, 50, 100)
       *   // [required]
       *   pageSize: number
       *   // 命名空间
       *   // [required]
       *   namespace: string
       *   // 键名
       *   // [required]
       *   key: string
       *   // 键值类型
       *   // [required]
       *   valueType: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // [required]
       *   code: number
       *   // [required]
       *   msg: string
       * } & unknown
       * ```
       */
      ConfigController_getConfigurations<
        Config extends Alova2MethodConfig<ResultData & unknown> & {
          data: ConfigurationPagniationDto;
        }
      >(
        config: Config
      ): Alova2Method<ResultData & unknown, 'Config.ConfigController_getConfigurations', Config>;
      /**
       * ---
       *
       * [GET] Get configuration by id
       *
       * **path:** /config/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // [required]
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      ConfigController_findOne<
        Config extends Alova2MethodConfig<unknown> & {
          pathParams: {
            /**
             * [required]
             */
            id: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<unknown, 'Config.ConfigController_findOne', Config>;
      /**
       * ---
       *
       * [PATCH] Update configuration
       *
       * **path:** /config/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // [required]
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 命名空间
       *   namespace?: string
       *   // 键名
       *   key?: string
       *   // 键值
       *   value?: string
       *   // 键值类型
       *   valueType?: string
       *   // 键描述
       *   description?: string
       *   // 是否公开
       *   isPublic?: boolean
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      ConfigController_update<
        Config extends Alova2MethodConfig<unknown> & {
          pathParams: {
            /**
             * [required]
             */
            id: string;
          };
          data: UpdateConfigDto;
        }
      >(
        config: Config
      ): Alova2Method<unknown, 'Config.ConfigController_update', Config>;
      /**
       * ---
       *
       * [DELETE] Delete configuration
       *
       * **path:** /config/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // [required]
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      ConfigController_remove<
        Config extends Alova2MethodConfig<unknown> & {
          pathParams: {
            /**
             * [required]
             */
            id: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<unknown, 'Config.ConfigController_remove', Config>;
    };
  }

  var Apis: Apis;
}
