/* tslint:disable */
/* eslint-disable */
/**
 * Gather Ends - version 1.0.0
 *
 * MoneyRoadGather EndPoints
 *
 * OpenAPI version: 3.0.0
 *
 * Contact:
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
import type { Alova, AlovaMethodCreateConfig, AlovaGenerics, Method } from 'alova';
import type { $$userConfigMap, alovaInstance } from '.';
import type apiDefinitions from './apiDefinitions';

type CollapsedAlova = typeof alovaInstance;
type UserMethodConfigMap = typeof $$userConfigMap;

type Alova2MethodConfig<Responded> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Omit<
        AlovaMethodCreateConfig<
          AlovaGenerics<Responded, any, RequestConfig, Response, ResponseHeader, L1Cache, L2Cache, SE>,
          any,
          Responded
        >,
        'params'
      >
    : never;

// Extract the return type of transform function that define in $$userConfigMap, if it not exists, use the default type.
type ExtractUserDefinedTransformed<
  DefinitionKey extends keyof typeof apiDefinitions,
  Default
> = DefinitionKey extends keyof UserMethodConfigMap
  ? UserMethodConfigMap[DefinitionKey]['transform'] extends (...args: any[]) => any
    ? Awaited<ReturnType<UserMethodConfigMap[DefinitionKey]['transform']>>
    : Default
  : Default;
type Alova2Method<
  Responded,
  DefinitionKey extends keyof typeof apiDefinitions,
  CurrentConfig extends Alova2MethodConfig<any>
> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Method<
        AlovaGenerics<
          CurrentConfig extends undefined
            ? ExtractUserDefinedTransformed<DefinitionKey, Responded>
            : CurrentConfig['transform'] extends (...args: any[]) => any
              ? Awaited<ReturnType<CurrentConfig['transform']>>
              : ExtractUserDefinedTransformed<DefinitionKey, Responded>,
          any,
          RequestConfig,
          Response,
          ResponseHeader,
          L1Cache,
          L2Cache,
          SE
        >
      >
    : never;

export type ResultData = {
  /**
   * [required]
   */
  code: number;
  /**
   * [required]
   */
  msg: string;
};
export type UserPagniationDto = {
  /**
   * 分页页码
   * [required]
   */
  page: number;
  /**
   * 分页大小(5, 10, 20, 50, 100)
   * [required]
   */
  pageSize: number;
  /**
   * 账号名称参数
   */
  name?: string;
  /**
   * 邮箱名称参数
   */
  email?: string;
};
export type UserLoginProps = {
  /**
   * [required]
   */
  account: string;
  /**
   * [required]
   */
  password: string;
  /**
   * [required]
   */
  type: string;
  /**
   * [required]
   */
  fingerprint: string;
  /**
   * [required]
   */
  platform: string;
};
declare global {
  interface Apis {
    App: {
      /**
       * ---
       *
       * [GET]
       *
       * **path:** /
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = string
       * ```
       */
      AppController_getHello<Config extends Alova2MethodConfig<string>>(
        config?: Config
      ): Alova2Method<string, 'App.AppController_getHello', Config>;
    };
    User: {
      /**
       * ---
       *
       * [GET] Get logined user info
       *
       * **path:** /user/info
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      UserController_getUserInfo<Config extends Alova2MethodConfig<unknown>>(
        config?: Config
      ): Alova2Method<unknown, 'User.UserController_getUserInfo', Config>;
      /**
       * ---
       *
       * [POST] Get users list
       *
       * **path:** /user/users
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 分页页码
       *   // [required]
       *   page: number
       *   // 分页大小(5, 10, 20, 50, 100)
       *   // [required]
       *   pageSize: number
       *   // 账号名称参数
       *   name?: string
       *   // 邮箱名称参数
       *   email?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // [required]
       *   code: number
       *   // [required]
       *   msg: string
       * } & unknown
       * ```
       */
      UserController_getUsers<
        Config extends Alova2MethodConfig<ResultData & unknown> & {
          data: UserPagniationDto;
        }
      >(
        config: Config
      ): Alova2Method<ResultData & unknown, 'User.UserController_getUsers', Config>;
      /**
       * ---
       *
       * [POST] Register
       *
       * **path:** /user/register
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      UserController_register<Config extends Alova2MethodConfig<unknown>>(
        config?: Config
      ): Alova2Method<unknown, 'User.UserController_register', Config>;
    };
    Auth: {
      /**
       * ---
       *
       * [POST] Login
       *
       * **path:** /auth/login
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // [required]
       *   account: string
       *   // [required]
       *   password: string
       *   // [required]
       *   type: string
       *   // [required]
       *   fingerprint: string
       *   // [required]
       *   platform: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      AuthController_login<
        Config extends Alova2MethodConfig<unknown> & {
          data: UserLoginProps;
        }
      >(
        config: Config
      ): Alova2Method<unknown, 'Auth.AuthController_login', Config>;
      /**
       * ---
       *
       * [POST] Refresh token
       *
       * **path:** /auth/refresh
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      AuthController_refresh<Config extends Alova2MethodConfig<unknown>>(
        config?: Config
      ): Alova2Method<unknown, 'Auth.AuthController_refresh', Config>;
      /**
       * ---
       *
       * [POST] Get user history (latest 10)
       *
       * **path:** /auth/history
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      AuthController_getHistory<Config extends Alova2MethodConfig<unknown>>(
        config?: Config
      ): Alova2Method<unknown, 'Auth.AuthController_getHistory', Config>;
    };
  }

  var Apis: Apis;
}
